services:
  - type: web
    name: knn-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn knn_backend.wsgi
    preDeployCommand: |
      python manage.py makemigrations
      python manage.py migrate
